<?php
// $Id$

/**
 * Implementation of hook_enable().
 */
function feeds_facebook_enable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}

/**
 * Implementation of hook_disable().
 */
function feeds_facebook_disable() {
  //clear the cache to display in Feeds as available plugin.
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
